"""add_sent_to_email_to_outreach_emails

Revision ID: c4bf91ea5e9c
Revises: 999dc3ba002e
Create Date: 2026-04-14 12:55:46.583697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bf91ea5e9c'
down_revision: Union[str, Sequence[str], None] = '999dc3ba002e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach_emails', sa.Column('sent_to_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach_emails', 'sent_to_email')
    # ### end Alembic commands ###
