"""add_email_type_to_outreach_emails

Revision ID: d563d29005d3
Revises: c4bf91ea5e9c
Create Date: 2026-04-14 14:34:07.568660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd563d29005d3'
down_revision: Union[str, Sequence[str], None] = 'c4bf91ea5e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach_emails', sa.Column('email_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach_emails', 'email_type')
    # ### end Alembic commands ###
