"""Add cities and pipeline_runs tables

Revision ID: da17a77ff560
Revises: 
Create Date: 2026-04-03 11:31:24.835730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da17a77ff560'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ulid')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ulid', sa.String(length=26), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logs', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ulid')
    )
    op.create_index(op.f('ix_pipeline_runs_city_id'), 'pipeline_runs', ['city_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.alter_column('leads', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column(
            'leads', 'created_at',
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
            postgresql_using="created_at::timestamp with time zone"
        )
    op.alter_column(
            'leads', 'updated_at',
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
            postgresql_using="updated_at::timestamp with time zone"
        )

    op.create_index(op.f('ix_leads_ai_score'), 'leads', ['ai_score'], unique=False)
    op.create_index(op.f('ix_leads_business_name'), 'leads', ['business_name'], unique=False)
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.create_index(op.f('ix_leads_priority'), 'leads', ['priority'], unique=False)
    op.create_index(op.f('ix_leads_segment'), 'leads', ['segment'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.alter_column('outreach_emails', 'lead_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('outreach_emails', 'subject',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('outreach_emails', 'generated_at',
               existing_type=sa.VARCHAR(),
                type_=sa.DateTime(timezone=True),
                existing_nullable=True,
                postgresql_using="generated_at::timestamp with time zone"
    )
    op.alter_column('outreach_emails', 'sent_at',
               existing_type=sa.VARCHAR(),
                type_=sa.DateTime(timezone=True),
                existing_nullable=True,
                postgresql_using="sent_at::timestamp with time zone"
    )
    op.create_index(op.f('ix_outreach_emails_lead_id'), 'outreach_emails', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'outreach_emails', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outreach_emails', type_='foreignkey')
    op.drop_index(op.f('ix_outreach_emails_lead_id'), table_name='outreach_emails')
    op.alter_column('outreach_emails', 'sent_at',
               existing_type=sa.VARCHAR(),
                type_=sa.DateTime(timezone=True),
                existing_nullable=True,
                postgresql_using="sent_at::timestamp with time zone"
    )
    op.alter_column('outreach_emails', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('outreach_emails', 'subject',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('outreach_emails', 'lead_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_segment'), table_name='leads')
    op.drop_index(op.f('ix_leads_priority'), table_name='leads')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_ai_score'), table_name='leads')
    op.alter_column('leads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('leads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('leads', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('leads', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_city_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
